---
- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  tasks:

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add Kubernetes APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes

  - name: Add Kubernetes GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Install required packages
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - docker.io
      state: present
      update_cache: yes

  - name: Enable and start Docker
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: Enable and start kubelet
    systemd:
      name: kubelet
      enabled: yes
      state: started

- name: Initialize Kubernetes Master
  hosts: master
  become: true
  tasks:

  - name: Get private IP of master
    shell: hostname -I | awk '{print $1}'
    register: private_ip

  - name: Initialize Kubernetes cluster using private IP
    command: kubeadm init --ignore-preflight-errors=all --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ private_ip.stdout }}
    register: kubeadm_init
    when: private_ip.stdout != ""

  - name: Create .kube directory
    file:
      path: /home/ubuntu/.kube
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0755

  - name: Copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Install Calico network plugin
    become: true
    become_user: ubuntu
    environment:
      KUBECONFIG: /home/ubuntu/.kube/config
    shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

  - name: Extract join command
    shell: kubeadm token create --print-join-command
    register: join_command

  - name: Save join command to file
    copy:
      content: "{{ join_command.stdout }}"
      dest: /tmp/kube_join.sh
      mode: 0755

- name: Join Worker Nodes to Cluster
  hosts: workers
  become: true
  tasks:

  - name: Copy join script from master
    fetch:
      src: /tmp/kube_join.sh
      dest: /tmp/kube_join.sh
      flat: yes
    delegate_to: master

  - name: Join worker node to cluster
    command: sh /tmp/kube_join.sh

