region: us-east-1
key_name: key1
instance_type: t2.micro
ami_id: ami-020cba7c55df1f615
vpc_id: vpc-0ae1d2116842f0dad
subnet_ids:
  - subnet-0bbcb1ac0974d1b3b
  - subnet-0ab5189bac5d1515e
security_group_ids:
  - sg-090cc69f6b4c9f3c8
